---
- include: install_zbx_db.yml tags=db
- include: install_mysql.yml tags=db
- include: install_zbx_web.yml tags=web
- inlcude: install_nginx.yml tags=web
- include: install_phpfdm.yml tags=web
- inlcude: install_zabbix_server tags=web
